@isTest
public class ADM_EmailSLACounterControllerTest {
    /*
     * DEPRECATED
     * 
	static testMethod void findWorkTest(){
         ADM_Work__c w1;
         ADM_Work__c w2;
            
         try{
         	DateTime expectedDateTime = DateTime.newInstance(2016, 12, 12,1,33,0);
            w1 = new ADM_Work__c();
            w1.Due_Date__c = expectedDateTime;
            w2 = new ADM_Work__c();
            w2.Due_Date__c = DateTime.now();
                        
            insert w1;
            insert w2;
            
            //Test here
            ADM_Work__c foundWork = ADM_EmailSLACounterController.findWork(w1.Name);
            System.assertEquals(expectedDateTime,foundWork.Due_Date__c,  'Search did not return the correct work item');
            
            //get rid of it
            delete w1;
            delete w2;
        }catch(Exception e){
            System.debug(e.getMessage());
        }
         
    }
*/
}