public with sharing class ADM_EmailSLACounterController {
    /*
     * DEPRECATED
     * See ADM_EmailWorkQuickViewController
     * 
    @AuraEnabled
    public static ADM_Work__c findWork(String workName) {
        if (!Schema.SObjectType.ADM_Work__c.fields.Due_Date__c.isAccessible()){
            return null;
        }
        return [SELECT Due_Date__c FROM ADM_Work__c Where Name=:workName LIMIT 1];
    }
	*/
}